### ISSUE TITLE
jittering is observed while testing on cam  and facial landmark shifted on large head pose 

### ISSUE THREAD

**Issue by joe0327** [facebookresearch/supervision-by-registration#10]
how to improve the problems above？how many training data do you use to reproduce the result you mentioned in the paper?

**Comment by D-X-Y** [comment]
For 300W, we use 300W and YoutubeFace; For 300VW, we use 300W, 300VW, and some internal data. To reduce the jitterring, did you feed the targe video into the training procedure as unlabeled data?

**Comment by joe0327** [comment]
I use 300W and 300VW data, the training data is about 3000 labeled and 3000 unlabeled. the more training data the batter results?

**Comment by D-X-Y** [comment]
Yes! The more training data you use, the better results you get. Note that one should carefully select the unlabeled videos w.r.t. the resolution, pose, and etc. More detailed discussion can be found in the paper.
