### ISSUE TITLE
How to test the sbr model ? 

### ISSUE THREAD

**Issue by qiexing** [facebookresearch/supervision-by-registration#11]
Dear author,
         I trained the sbr model. To test the model, I simply replace the cpm model name to sbr model name like this:
     
 python ./exps/eval.py --image ./cache_data/cache/demo-sbrs/image0001.png --model ./snapshots/CPM-SBR/checkpoint/cpm_vgg16-epoch-006-050.pth --face 5 5 450 680 --save ./cache_data/cache/test.jpeg
       But it reported errors:
![image](https://user-images.githubusercontent.com/8178397/42151637-3208afc0-7e10-11e8-98e2-06b12682ca37.png)
      Do you know how to solve this problem ?

**Comment by qiexing** [comment]
Problem solved. 
Change the script in:
1. Load with LK model 
2. Forward with LK.detector branch
Here is my modified script:

[eval_kate_sbr.zip](https://github.com/facebookresearch/supervision-by-registration/files/2154368/eval_kate_sbr.zip)

**Comment by Coolxiaolin** [comment]
can you share your pretrained weights?
