### ISSUE TITLE
What detector do you use?

### ISSUE THREAD

**Issue by Dugudaibo** [facebookresearch/supervision-by-registration#12]
When training in video, it should use a face detector to detect where is the face. What detector do you use and where is it in the code.
thank you ~

**Comment by D-X-Y** [comment]
We use the convolution pose machine (CPM) with the base model of VGG16 in the paper. (https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/models/cpm_vgg16.py)

**Comment by Dugudaibo** [comment]
OK ~thank you ~~~

**Comment by D-X-Y** [comment]
You are welcome~
