### ISSUE TITLE
Where is Reg?

### ISSUE THREAD

**Issue by Dugudaibo** [facebookresearch/supervision-by-registration#13]
In the paper ,"The second detector is a simple regression network, denoted as Reg."Is it in the code?I only find CMP.
When I set satage = 0, is it Reg?

**Comment by D-X-Y** [comment]
No. The Reg is a different network, where the output is a 2-D vector instead of the heat-map. It is just used to verify SBR can be applied for different kinds of detectors. Reg needs different training codes and we do not include that in this GitHub project.

**Comment by Dugudaibo** [comment]
If I want to use a simple net to replace cpm_VGG16，what should I do?
If I just use a simple net to replace cpm_VGG16 in cpm_vgg16.py, is it ok?

**Comment by D-X-Y** [comment]
Suppose the name of our network is SIMPLE. One way is to add the SIMPLE.py in https://github.com/facebookresearch/supervision-by-registration/tree/master/lib/models. And in https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/models/basic.py, add SIMPLE to the obtain_model function. Then you can simply change the arch parameter in https://github.com/facebookresearch/supervision-by-registration/blob/master/configs/Detector.config and train your model (suppose your network use the heatmap output).

**Comment by Dugudaibo** [comment]
If I only use a net with convolution, such as VGG16，should I do as above?

**Comment by D-X-Y** [comment]
Yes, no matter what network you use.

**Comment by Dugudaibo** [comment]
Thank you and I have a very simple error which may be easy but bothers me for a long time.
When I evaluate on  one image , the error(NME) is about 0.024. However , on the paper,  the NME of 300W is 3.28. Did you sum the NME of all images in 300-w ?Or I calculate it in a wrong method.

**Comment by D-X-Y** [comment]
In the paper, 3.28 means 3.28%, equals to 0.0328. In the paper, I average the NME on all images of 300W.

**Comment by Dugudaibo** [comment]
Thank you very very very much~~~~~~~

**Comment by D-X-Y** [comment]
You are welcome~
