### ISSUE TITLE
About the example of data list

### ISSUE THREAD

**Issue by cenaliu** [facebookresearch/supervision-by-registration#14]
Thanks for providing this good code, while I can't find an example of demo-sbr.lst or 300w.train.DET in your code, only a format. Would your please provide an example of these list. Does demo-sbr.lst need to be video sequences. Thanks very much!

**Comment by D-X-Y** [comment]
Hi, please follow the instruction in https://github.com/facebookresearch/supervision-by-registration/tree/master/cache_data. The 300w.train.DET is generated by run `python generate_300W.py`. demo-sbr.lst is generated by run `python demo_list.py`
