### ISSUE TITLE
About 300VW Experiments

### ISSUE THREAD

**Issue by cenaliu** [facebookresearch/supervision-by-registration#15]
Hi, @D-X-Y. Thanks again for your excellent help and this fantastic code! Now I can generate all the training and testing lists of 300VW. But I am still wondering how to use these lists and reproduce the results of 300VW in this good paper. Do I need the model pretrained on 300W? Would you please  share the 300VW training scripts, Thanks very much!

**Comment by D-X-Y** [comment]
You can train the model on 300W, Youtube Face, and 300VW. You should observe improvements compared to training on 300W and 300VW. In our experiments, we use some internal data, and these data can not be shared.

**Comment by cenaliu** [comment]
@D-X-Y Thanks very much! I already used all 300W dataset and  300VW training dataset to train a good baseline.  Would you please tell me some details of using SBR to refine CNN model?  I saw that each video of 300VW has an unsupervised list with ".none " suffix. But I don't know how to use these lists for SBR training, Do I need to use them all or use them one by one? Thanks very much!

**Comment by D-X-Y** [comment]
Hi, sorry for the late reply. For the better performance, you can use them one by one. To use SBR to refine CNN models, you can replace the './cache_data/lists/demo/demo-sbr.lst' in demo_sbr.sh by the generated ".none" list file.

**Comment by cenaliu** [comment]
@D-X-Y Thanks very much, your suggestion successfully solved my confusion.

**Comment by D-X-Y** [comment]
You are welcome :)
