### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by gufeng1329** [facebookresearch/supervision-by-registration#16]
Hi, @D-X-Y. Thanks for your fantastic code! I found results of basic training with your code are better than the results mentioned in the paper. Would you provide your results of cpm and cpm+sbr? Thank you very much!

**Comment by D-X-Y** [comment]
Hi, we fixed some small issues in this code and thus can obtain slightly better performance than that of in paper. We will report the new results in our extension version (still in progress). Thanks a lot.
