### ISSUE TITLE
About facial landmark detector

### ISSUE THREAD

**Issue by HonestoLiu** [facebookresearch/supervision-by-registration#18]
Thanks for your sharing! If my basic facial landmark detector is not based on neural network, such as SDM ,LBF , how can I embed the LK tracking operation?

**Comment by D-X-Y** [comment]
It could be difficult to embed the LK tracking. Do you implement SDM in PyTorch?

**Comment by HonestoLiu** [comment]
No, I don't. Thanks for your reply.
