### ISSUE TITLE
training params

### ISSUE THREAD

**Issue by NikolayTV** [facebookresearch/supervision-by-registration#19]
Hi. When I run: 
sh scripts/300W-DET.sh 

I get the following error:

Main Function with logger : Logger(dir=snapshots/300W-CPM-DET)
Arguments : -------------------------------
arg_flip         : False
batch_size       : 8
crop_height      : 256
crop_perturb_max : 30
crop_width       : 256
data_indicator   : 300W-68
error_bar        : None
eval_ilists      : ['./cache_data/lists/300W/300w.test.common.DET', './cache_data/lists/300W/300w.test.challenge.DET', './cache_data/lists/300W/300w.test.full.DET']
eval_once        : False
eval_vlists      : None
heatmap_type     : gaussian
model_config     : ./configs/Detector.config
num_pts          : 68
opt_config       : ./configs/SGD.config
pre_crop_expand  : 0.2
print_freq       : 100
rand_seed        : 88375
rotate_max       : 20
save_path        : ./snapshots/300W-CPM-DET
scale_eval       : 1.0
scale_max        : 1.1
scale_min        : 0.9
scale_prob       : 1.0
sigma            : 4.0
train_lists      : ['./cache_data/lists/300W/300w.train.DET']
workers          : 8
Python  version : 3.6.0 (default, Jun 24 2018, 18:51:20)  [GCC 5.4.0 20160609]
Pillow  version : 4.3.0
PyTorch version : 0.4.0
cuDNN   version : 7102
./configs/Detector.config
Configure(arch='cpm_vgg16', stages=3, dilation=[1], pooling=[True, True, True], downsample=8, argmax=4, pretrained=[True])
Real Sigma : 4.0
The general dataset initialization done : GeneralDataset(point-num=-1, sigma=4.0, heatmap_type=gaussian, length=0, dataset=300W-68)
Function [load_lists] input 1 files
Load [0/1]-th list : ./cache_data/lists/300W/300w.train.DET with 3148 images
GeneralDataset : load-list : load 3148 lines
[GeneralDataset] load-data 3148 datas begin
Load data done for the general dataset, which has 3148 images.
The general dataset initialization done : GeneralDataset(point-num=-1, sigma=4.0, heatmap_type=gaussian, length=0, dataset=300W-68)
Function [load_lists] input 1 files
Load [0/1]-th list : ./cache_data/lists/300W/300w.test.common.DET with 554 images
GeneralDataset : load-list : load 554 lines
[GeneralDataset] load-data 554 datas begin
Load data done for the general dataset, which has 554 images.
The general dataset initialization done : GeneralDataset(point-num=-1, sigma=4.0, heatmap_type=gaussian, length=0, dataset=300W-68)
Function [load_lists] input 1 files
Load [0/1]-th list : ./cache_data/lists/300W/300w.test.challenge.DET with 135 images
GeneralDataset : load-list : load 135 lines
[GeneralDataset] load-data 135 datas begin
Load data done for the general dataset, which has 135 images.
The general dataset initialization done : GeneralDataset(point-num=-1, sigma=4.0, heatmap_type=gaussian, length=0, dataset=300W-68)
Function [load_lists] input 1 files
Load [0/1]-th list : ./cache_data/lists/300W/300w.test.full.DET with 689 images
GeneralDataset : load-list : load 689 lines
[GeneralDataset] load-data 689 datas begin
Load data done for the general dataset, which has 689 images.
configure : Configure(arch='cpm_vgg16', stages=3, dilation=[1], pooling=[True, True, True], downsample=8, argmax=4, pretrained=[True])
Initialize cpm-vgg16 with configure : Configure(arch='cpm_vgg16', stages=3, dilation=[1], pooling=[True, True, True], downsample=8, argmax=4, pretrained=[True])
vgg16_base use pre-trained model
Traceback (most recent call last):
  File "./exps/basic_main.py", line 181, in <module>
    main(args)
  File "./exps/basic_main.py", line 95, in main
    net = obtain_model(model_config, args.num_pts + 1)
  File "/home/nikolaytv/workspace/python3/supervision-by-registration/lib/models/basic.py", line 12, in obtain_model
    net = cpm_vgg16(configure, points)
  File "/home/nikolaytv/workspace/python3/supervision-by-registration/lib/models/cpm_vgg16.py", line 114, in cpm_vgg16
    weights = model_zoo.load_url(model_urls)
  File "/home/nikolaytv/.virtualenvs/SAN/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 66, in load_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/nikolaytv/.virtualenvs/SAN/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/nikolaytv/.virtualenvs/SAN/lib/python3.6/site-packages/torch/serialization.py", line 476, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: unexpected EOF. The file might be corrupted.

**Comment by D-X-Y** [comment]
Hi, would you mind to delete your downloaded vgg16 model, and re-run the code? It seems that your pre-trained model is broken.

**Comment by NikolayTV** [comment]
TY for answer. I did not download any pretrained model. Do I need to? I just followed readme and made dataset  with "python generate_300W.py"
Or I gave vgg16 somwere in the cache and i have to find and remove it?

**Comment by D-X-Y** [comment]
No need to download manually, `model_zoo.load_url` will download it automatically, however sometimes if you stop the code during downloading, it may leave a broken model file and the next time you run the code, it may think you already have the pre-trained model and use that broken model file. In that case, you will get this error.

**Comment by NikolayTV** [comment]
I tryed to reinstall torch and reclone your git, nothing changed. Where is it located, so i can delete it manually?

**Comment by D-X-Y** [comment]
https://pytorch.org/docs/stable/_modules/torch/utils/model_zoo.html#load_url
According to the PyTorch document, its default path is 
```
torch_home = os.path.expanduser(os.getenv('TORCH_HOME', '~/.torch'))
model_dir = os.getenv('TORCH_MODEL_ZOO', os.path.join(torch_home, 'models'))
```
