### ISSUE TITLE
how to test my video

### ISSUE THREAD

**Issue by JWSunny** [facebookresearch/supervision-by-registration#20]
hello,

How to directly use CPM-SBR（CPM-SBR） to predict the key points of a face in my own video, which code can I refer to?

Thanks，best wishes~

**Comment by D-X-Y** [comment]
First of all, for facial key points detection, we assume the face bounding box location is available. Then, you should first train CPM by https://github.com/facebookresearch/supervision-by-registration/blob/master/scripts/300W-DET.sh , then train CPM+SBR on your own video, by using https://github.com/facebookresearch/supervision-by-registration/blob/master/scripts/demo_sbr.sh (you need to modify some parameters).

**Comment by JWSunny** [comment]
Thanks for quickly response. 

Now, I trained 300W-DET.sh and demo_sbr.sh. According to this process, I can get the video demo-sbr-vis.mp4. However, if I now give a video file, how can I use CPM-SBR to directly obtain the key points of the face in the video? Or what code can I refer to?

**Comment by D-X-Y** [comment]
You can refer to `https://github.com/facebookresearch/supervision-by-registration/blob/master/cache_data/demo_list.py`, this code extracts each frame of the demo video, and generate the corresponding label file.

**Comment by JWSunny** [comment]
There is a question about evaluating CPM-SBR. I used the CPM-SBR model when making a picture prediction:
"python ./exps/eval.py --image ./cache_data/cache/self.jpeg --model ./snapshots/CPM-SBR/checkpoint/cpm_vgg16-epoch-049-050.pth --face 250 150 900 1100 --save ./cache_data/cache/test.jpeg"
But there was an error:

 File "./exps/eval.py", line 88, in <module>
    evaluate(args)
  File "./exps/eval.py", line 50, in evaluate
    net.load_state_dict(weights)

    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGG16_base:
	Missing key(s) in state_dict: "features.0.weight", "features.0.bias", "features.2.weight", "features.2.bias", "features.5.weight", "features.5.bias", "features.7.weight", "features.7.bias", "features.10.weight", "features.10.bias", "features.12.weight", "features.12.bias", "features.14.weight", "features.14.bias", "features.17.weight", "features.17.bias", "features.19.weight", "features.19.bias", "features.21.weight", "features.21.bias", "CPM_feature.0.weight", "CPM_feature.0.bias", "CPM_feature.2.weight", "CPM_feature.2.bias", "stages.0.0.weight", "stages.0.0.bias", "stages.0.2.weight", "stages.0.2.bias", "stages.0.4.weight", "stages.0.4.bias", "stages.0.6.weight", "stages.0.6.bias", "stages.0.8.weight", "stages.0.8.bias", "stages.0.10.weight", "stages.0.10.bias", "stages.1.0.weight", "stages.1.0.bias", "stages.1.2.weight", "stages.1.2.bias", "stages.1.4.weight", "stages.1.4.bias", "stages.1.6.weight", "stages.1.6.bias", "stages.1.8.weight", "stages.1.8.bias", "stages.1.10.weight", "stages.1.10.bias", "stages.1.12.weight", "stages.1.12.bias", "stages.1.14.weight", "stages.1.14.bias", "stages.1.16.weight", "stages.1.16.bias", "stages.2.0.weight", "stages.2.0.bias", "stages.2.2.weight", "stages.2.2.bias", "stages.2.4.weight", "stages.2.4.bias", "stages.2.6.weight", "stages.2.6.bias", "stages.2.8.weight", "stages.2.8.bias", "stages.2.10.weight", "stages.2.10.bias", "stages.2.12.weight", "stages.2.12.bias", "stages.2.14.weight", "stages.2.14.bias", "stages.2.16.weight", "stages.2.16.bias".

**Comment by JWSunny** [comment]
Problem solved. Thanks

I want to know the current detection speed of CPM-SBR, how many fps can be achieved when processing video, have you tested it?

**Comment by JWSunny** [comment]
hello,
1. I want to know the current detection speed of CPM-SBR, how many fps can be achieved when processing video, have you tested it?
2. i'll use the 300W dataset 、 300VW_train and some unlabled videos about 300VW to train CPM-SBR, more videos to be fed will cost more time， do you know how many videos is suitable.（3 GPU 1080ti）

Thanks.

**Comment by D-X-Y** [comment]
I didn't test the fps, while the log will print the roughly time cost on the whole dataset (you can divide the time cost by the number of images to calculate the fps). 
I tried Youtubu face dataset, but it requires some filtration. You can also use the video datasets for pose estimation and apply one face detector on them. DIfferent videos may need specific parameter tuning.
