### ISSUE TITLE
Can it be converted to real-time detection?

### ISSUE THREAD

**Issue by Dawson-huang** [facebookresearch/supervision-by-registration#21]
Hello, thank you for your job!
Like this title,  can it be converted to real-time detection ? 
Looking forward to your reply！

**Comment by D-X-Y** [comment]
Hi, it can be used for real-time detection. While before applying, one usually need to first train it on videos which cost much time.

**Comment by JWSunny** [comment]
@D-X-Y hello,
i am training the model in 300VW datasets， how can i use the CPM-SBR model to real-time predict facial landmars on a video. Looking forward to your replay.
Thanks, best wishes.

**Comment by D-X-Y** [comment]
You need to first extract every frame of that video, and use the trained model to predict on each frame. See https://github.com/facebookresearch/supervision-by-registration#evaluation , if you want the input being a video, you need to modify the code.
