### ISSUE TITLE
real-time prediction

### ISSUE THREAD

**Issue by JWSunny** [facebookresearch/supervision-by-registration#22]
hello，
thanks to your sharing，i want to konw can it predict the facial landmarks in a video！
thanks，best wishes

**Comment by D-X-Y** [comment]
Yes, it can. The trained detector can be applied frame by frame.

**Comment by JWSunny** [comment]
i see the mp4 file is dealed to lst file，then predict，and ffmpeg deals with the frames convert mp4 file.
have it any code to directly deal the mp4 file？and can you provide the speed of dealing one frame！

**Comment by D-X-Y** [comment]
Sorry, this repo does not deal with video data directly. The roughly time cost is provided here https://github.com/facebookresearch/supervision-by-registration/issues/9.

**Comment by JWSunny** [comment]
thanks，i test the code in images and video，100ms about per image，but 450ms about per frame
