### ISSUE TITLE
error  ''CUDA is not available.''

### ISSUE THREAD

**Issue by Brystone** [facebookresearch/supervision-by-registration#24]
I am very happy to see this paper. There was a problem when running the code. My computer only supports pytorch without cuda. How can I successfully run the code on this version?

**Comment by D-X-Y** [comment]
Hi, without CUDA, it costs unaffordable time for training and test. If you want to use the CPU mode, please remove the `.cuda()` in https://github.com/facebookresearch/supervision-by-registration/blob/master/exps/eval.py#L48, and other related codes.
