### ISSUE TITLE
Imitate your project and have problems

### ISSUE THREAD

**Issue by Dawson-huang** [facebookresearch/supervision-by-registration#25]
Hello, thank you for your project again!
I mimicked your project that using the ratio of coordinates to the border as the label to regression training, and you used the actual coordinates as the label. But the points that my trained model detects are not as stable as your model. Can't use the ratio as a label?　
Notes: My tracking uses actual coordinates to track and then convert to ratio.

**Comment by D-X-Y** [comment]
The location difference of on keypoint in two consecutive frames is usually very small, such as 3 pixels. When converting it into a ratio, the difference may become much smaller, e.g., 0.001. In my opinion, the outputs of the deep model may not be able to be sensitive to small decimal.

**Comment by Dawson-huang** [comment]
Yes, you are right!
I had already tried kinds of way to achieve your project to apply my code but it failed, I think I had already understand the tracking loss calculation of your project then coding to my project. Now I think that converting keypoint to ratio maybe wrong!
Another question, Can I use the smaller Network instead of your VGG heatmap Network? Such as 48*48 Network which is three or four Convolution layer.

**Comment by D-X-Y** [comment]
Yes, of course, you can use a smaller network, while a large model usually yields better performance.

**Comment by pengcheng93** [comment]
> Yes, of course, you can use a smaller network, while a large model usually yields better performance.

Hello！ I have a question about Reg in your paper. The Reg network directly outputs the absolute coordinates of the landmarks without normalize? Can LK operation be replaced by other optical flow algorithm?

**Comment by D-X-Y** [comment]
Not the mean of heatmaps. In https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/datasets/GeneralDataset.py#L161, the dataset will return a `points` variable. The target of the Reg network is to predict the `points` variable. `points` represents the coordinates of each landmark.

**Comment by pengcheng93** [comment]
> Not the mean of heatmaps. In https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/datasets/GeneralDataset.py#L161, the dataset will return a `points` variable. The target of the Reg network is to predict the `points` variable. `points` represents the coordinates of each landmark.

absolute coordinates of landmarks? Can LK operation be replaced by other optical flow algorithm?

**Comment by D-X-Y** [comment]
The coordinates should be normalized into 0~1. Yes, it can be replaced by other optical flow algorithms that allow back-propagation.
