### ISSUE TITLE
how to run demo_list.py?

### ISSUE THREAD

**Issue by tongxinjie** [facebookresearch/supervision-by-registration#26]
I have some problems when I try to get the demo-sbr.lst. I download your project and run demo_list.py, but  there is no file in .\supervision-by-registration-master\cache_data\cache\demo-sbrs. The code says there should be a file with 275 images, what should I fill in this folder?

**Comment by D-X-Y** [comment]
Please follow the README in here https://github.com/facebookresearch/supervision-by-registration/tree/master/cache_data#a-short-demo-video-sequence You need to extract frames into `./cache/demo-sbrs/` by ffmpeg at first.

**Comment by tongxinjie** [comment]
Oh! Thank u very much!
