### ISSUE TITLE
About Reg network

### ISSUE THREAD

**Issue by pengcheng93** [facebookresearch/supervision-by-registration#29]
## Issue description

Hello!
I have some question about the Reg network mentioned in your paper. Does the Reg network directly output absolute coordinate of landmarks without normalize? Can LK operation be replace by other optical flow algorithm?

**Comment by D-X-Y** [comment]
The Reg network directly predicts the coordinates normalized into 0-1.
Yes, LK can be replaced by any other optical flow algorithms that allow back-propagation.
