### ISSUE TITLE
pretrained model?

### ISSUE THREAD

**Issue by NikolayTV** [facebookresearch/supervision-by-registration#30]
Hi, can you share pretrained model?

**Comment by D-X-Y** [comment]
You can find the pre-trained model from here https://drive.google.com/open?id=1ylMoVuUaNPqP7GSeWS3yE-wfU9JEJSSu . Let me know if you have further questions.

**Comment by sljlp** [comment]
when i load the model, following error shows:
Traceback (most recent call last):
  File "./exps/eval-sbr.py", line 41, in <module>
    main(args)
  File "./exps/eval-sbr.py", line 25, in main
    evaluate(tempargs)
  File "/home1/jiabob/liupeng/fastface/fastface6.20/sbr/supervision-by-registration-master/exps/eval.py", line 54, in evaluate
    weights = remove_module_dict(snapshot['detector'])
KeyError: 'detector'
Could you please help me solve this problem?

**Comment by D-X-Y** [comment]
@sljlp  Would you mind providing the command that you run?

**Comment by sljlp** [comment]
Firstly thanks for your reply  @D-X-Y. 
The model saved by myself has the key 'detector',the values of which seem the same as ones of  'state_dict'. However, when I loaded the pretrained model you provided and printed the keys , I found there is no key named 'detector'. So I changed the 'detector' into 'state_dict' in codes  and it ran successfully.
the changed line is :
weights = remove_module_dict(snapshot['state_dict'])
at line 59(about) in file ./exps/eval.py
Could you please tell me whether it's OK?

**Comment by D-X-Y** [comment]
@sljlp Yes, it is ok. This is a problem caused by the inconsistency between different code versions. Sorry for the inconvenience.
