### ISSUE TITLE
Error for eval.py 

### ISSUE THREAD

**Issue by NikolayTV** [facebookresearch/supervision-by-registration#31]
I want to run pretrainded model on image to get landmarks.
I placed downloaded model im .snapshots/ folder.
OS Ubuntu 16.04

And when I run:
python ./exps/eval.py --image ./cache_data/cache/self.jpeg --model snapshots/300W-CPM-DET/checkpoint/cpm_vgg16-epoch-049-050.pth --face 250 150 900 1100 --save ./cache_data/cache/test.jpeg 

I get following error:

The image is ./cache_data/cache/self.jpeg 
The model is snapshots/300W-CPM-DET/checkpoint/cpm_vgg16-epoch-049-050.pth 
The face bounding box is [250.0, 150.0, 900.0, 1100.0] 
Traceback (most recent call last):   File "./exps/eval.py", line 88, in <module>     evaluate(args)   
File "./exps/eval.py", line 34, in evaluate     snapshot = torch.load(snapshot)   
File "/home/nikolaytv/.virtualenvs/VEmain/lib/python3.5/site-packages/torch/serialization.py", line 301, in load     f = open(f, 'rb') TypeError: invalid file: PosixPath('snapshots/300W-CPM-DET/checkpoint/cpm_vgg16-epoch-049-050.pth')

**Comment by NikolayTV** [comment]
When i change 34 line from   
snapshot = torch.load(shapshot)
to
snapshot = torch.load(args.model)

I get another error
![image](https://user-images.githubusercontent.com/32233366/47349974-f8cbf500-d6de-11e8-9268-718edcaa459b.png)

**Comment by D-X-Y** [comment]
Sorry for the late reply. I will check this soon.

**Comment by NikolayTV** [comment]
I fixed error by changing
`image = draw_image_by_points(args.image, prediction, 2, (255, 0, 0), args.face, resize)
`
on
`image = draw_image_by_points(Image.open(args.image), prediction, 2, (255, 0, 0), args.face, resize)
`

And also I had to redownload vgg model in torch lib, it was corrupt.
Now it works well

**Comment by D-X-Y** [comment]
👍 👍 👍
