### ISSUE TITLE
Some questions about preparing data

### ISSUE THREAD

**Issue by tongxinjie** [facebookresearch/supervision-by-registration#32]
Thank you for your sharing again.
I read your codes and find that when generating the AFLW, you use the 'mask_new' which defines the visibility of the labels, and only save the visible points into the .pts files. During the training procedure, you set the invisible points into zeros. If the original image has many occlusions, there would be few visible points during the training. I'm very curious about whether this would reduce the information for the cnn module?
Besides, when computing the nmes, the groundtruth will have many zeros as well. Will this affects the final results?

**Comment by D-X-Y** [comment]
Hi, I think this will not reduce the information, if we incorporate invisible points into the training procedure, it may feed wrong information into the CNN model.
During the evaluation, only the visible points are used to calculate the NME.
