### ISSUE TITLE
landmarks still shake after 10 epochs

### ISSUE THREAD

**Issue by Racha1992** [facebookresearch/supervision-by-registration#34]
## Issue description
Hi! How. many epochs did you train? I trained for about 10 epochs on 50 300VW videos, but the actual effect is not obvious, landmarks still shake

**Comment by D-X-Y** [comment]
Hi, would you mind to show me the log? what kinds of data do you use to training the model? I train SBR more than 50 epochs by using 300W+300VW+YouTube-Face.

**Comment by Racha1992** [comment]
I use 300W+300VW.  Loss drops by 25%.  Maybe it's not enough... but training procedure is so slow TAT

**Comment by D-X-Y** [comment]
Unfortunately, the codes are not optimized for efficiency. We are preparing for releasing an accelerated version and the new codes will come in two or three months.

**Comment by Racha1992** [comment]
Thanks for reply! Looking forward for it

**Comment by Racha1992** [comment]
Excuse me, shall you share your lk train log? I change the base network and the loss so that it produces the coordinates instead of landmark heatmaps. May I refer to your log so that I can know my project is right or not. Thanks!

**Comment by D-X-Y** [comment]
Hi @wangbingcan1990, it has been almost one year since I trained LK. I tried but did not find the log. Would you mind to show me your training log ? and maybe I can give some suggestions.

**Comment by Racha1992** [comment]
@D-X-Y  Thanks for your 'trying out' haha. Would you mind give me your email? Maybe sending my log files to you is a better way as there is too much content to display here.

**Comment by wangbingcan1990** [comment]
I can describe it roughly here.  At the begining of training with sbr, lk-loss is about 0.60, and it drops to  0.520 after 18 epochs. From epoch 12 to epoch 18 it decreases from 0.541 to 0.521.  I doubt if the rate of loss reduction is right.  lr is 1e-4, the same with yours, and lk_loss accounts for about 50% of total loss.

**Comment by Racha1992** [comment]
I can describe it roughly here. At the begining of training with sbr, lk-loss is about 0.60, and it drops to 0.520 after 18 epochs. From epoch 12 to epoch 18 it decreases from 0.541 to 0.521. I doubt if the rate of loss reduction is right. lr is 1e-4, the same with yours, and lk_loss accounts for about 50% of total loss. Trainset is 300W, 300VW and YouTubeFaces.

**Comment by D-X-Y** [comment]
Hi @wangbingcan1990 , my email is Xuanyi.Dong@student.uts.edu.au, feel free to contact me.
How about your detection loss? In addition, YouTubeFaces has a lot of noise, and you should better filter some low-resolution videos.

**Comment by Racha1992** [comment]
@D-X-Y Hi, my detection loss is normalized l2 loss, different from your heatmap loss. When train with SBR, detection loss rises a little. I agree with your sugesstion, and I will filter the videos.  Thank u!

**Comment by D-X-Y** [comment]
You are welcome~ What is the number of your L2 loss? Since you use a different loss, one should also adjust the loss weight.

**Comment by D-X-Y** [comment]
Close because of no further response in 7 days.
