### ISSUE TITLE
Training landmark detectors using my own dataset such as 300W-LP

### ISSUE THREAD

**Issue by SunnyDp** [facebookresearch/supervision-by-registration#36]
If I want to repeat the training procedure using the dataset like 300W-LP, which means 300W-Large pose, but the face detectors like dlib can't the large pose faces(-90 degree/90 degree), so without the detector results how can i get the  boundingboxes? Because the ‘bounding_boxes_lfpw_testset.mat‘ is necessary in your project. Only the landmark groudtruth is enough or not？Looking forward to your reply.

**Comment by D-X-Y** [comment]
Hi, Only the landmark groudtruth is enough. You can use a tiny bounding box generated from landmark ground truth as the detection results, for example: this function https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/datasets/dataset_utils.py#L115.
