### ISSUE TITLE
The loss between 'batch_location' and the groundtruth  

### ISSUE THREAD

**Issue by SunnyDp** [facebookresearch/supervision-by-registration#37]
Thanks for your great work. I want to compute the loss between the 'batch_location' and the gt to replace the loss between the output heatmap and the target heatmap. But the 'batch_location'  is computed in the function 'find_tensor_peak_batch.py'  which used torch.max() the find the max value position, I think the gradient can't be back propagated. Am I right? Waiting for your reply.

**Comment by D-X-Y** [comment]
No, 'batch_location' can back propagte gradients to 'heatmap'. As https://github.com/facebookresearch/supervision-by-registration/blob/master/lib/models/basic_batch.py#L43, the batch_locations is computed by two parts, i.e., sub_feature (which can be considered as a part of heatmap) and index (from torch.max). 'index' can not backpropagate gradients but 'sub_feature' can.
