### ISSUE TITLE
Reproducing quality of detection comparable with demo.gif

### ISSUE THREAD

**Issue by Daiver** [facebookresearch/supervision-by-registration#39]
Hi guys! Thank you for great project.
How can i train detector with quality comparable with demo.gif?
![demo](https://user-images.githubusercontent.com/754887/53325168-b7995b00-38f3-11e9-845b-e5889dd45b6e.gif)

I've tried to train regular detector by using `bash scripts/300W-DET.sh`, and SBR detector by `bash scripts/demo_sbr.sh` (according to the readme).

After that i tried to apply regular detector to test image.
`python3 ./exps/eval.py --image ./cache_data/cache/self.jpeg --model ./snapshots/300W-CPM-DET/checkpoint/cpm_vgg16-epoch-049-050.pth --face 250 150 900 1100 --save ~/test.jpeg`

![test](https://user-images.githubusercontent.com/754887/53325069-799c3700-38f3-11e9-90ee-6b17fa302293.jpeg)

And improved detector
`python3 ./exps/eval.py --image ./cache_data/cache/self.jpeg --model ./snapshots/CPM-SBR/checkpoint/cpm_vgg16-epoch-049-050.pth --face 250 150 900 1100 --save ~/test2.jpeg`

![test2](https://user-images.githubusercontent.com/754887/53325071-7b65fa80-38f3-11e9-87cf-80075fc081ad.jpeg)

I can see some improvement, but quality of both examples seems quite bad. I suppose that i used wrong datasets/settings. 

Thank you!

**Comment by D-X-Y** [comment]
Sorry for the late reply.
The model for demo.gif is trained on the internal datasets, which cannot be public. To maximize the performance of SBR, you need to train it on a large number of unlabeled videos and some annotated images. Specifically, the quality (such as resolution) of videos should be consistent with the test images/frames.

**Comment by Daiver** [comment]
Hi @D-X-Y ! Thank you for answer. Can i ask you what is the minimal number of labeled/unlabeled images to obtain similar results?
Anyway, thank you for answer and for really interesting paper.

**Comment by D-X-Y** [comment]
The number of unlabeled frames should be 10X larger than the number of labeled images. In addition, it is better to include unlabeled evaluation videos during training (see PAM in the paper).
Thanks very much for your recognition.

**Comment by Daiver** [comment]
Thank you!
