### ISSUE TITLE
Can I use my own video to test the cpm-sbr?

### ISSUE THREAD

**Issue by dyther** [facebookresearch/supervision-by-registration#40]
Thanks for your great project.
I have run the demo_sbr.sh and I can see the cpm detector has improved a lot on demo-sbr,mp4.
Now I want to use another video to test the detector , can I directly use the existent model? or  should  I retrain the model on another video?
If I can use the trained model on any videos?

**Comment by D-X-Y** [comment]
You need to retrain the model on another video. If you want to use the trained model on any video, it requires to train this model on a very large number of videos.

**Comment by dyther** [comment]
So,it cant be used for real-time detection? for the LK Operationr is a little slow

**Comment by D-X-Y** [comment]
After training, the learned detector can be used for real-time detection, since the inference procedure does not require the LK operator. (We are working on improving this algorithm including speeding up the LK, and will be public available soon)
