### ISSUE TITLE
evaluate the 300W video

### ISSUE THREAD

**Issue by cploveflower** [facebookresearch/supervision-by-registration#44]
I have train the sbr model with the 300W+demo-sbr,I know the train process have the evaluation with the demo-sbr,now I want to evaluate with a video in 300w,what should I do,I just see the evaluate on the single picture,didn't see the evaluation on the video,Thank you!

**Comment by D-X-Y** [comment]
There are two ways:
(1) https://github.com/facebookresearch/supervision-by-registration/tree/master/cache_data#300vw will generate a list file for 300VW, you can add this list file at this line when using this script https://github.com/facebookresearch/supervision-by-registration/blob/master/scripts/300W-DET.sh#L4

(2) extract all frames of a video on 300VW, and then evaluate them one by one as image.
