### ISSUE TITLE
confused about the NMS

### ISSUE THREAD

**Issue by wqz960** [facebookresearch/supervision-by-registration#45]
Hi! @D-X-Y Thank you for your wonderful code! But there is  a problem about NMS. In your code the Evaluation error is normalized by interouclar `if num_points == 68:
      interocular_distance = np.linalg.norm(ground_truth_points[:2, 36] - ground_truth_points[:2, 45])` but I watched some other codes, where this normal style seems to be normalized by corners. The true interouclar style in some codes is something like this: `if num_points == 68:
      interocular_distance = np.linalg.norm(np.mean(ground_truth_points[:2, 36:42],axis=0) - np.mean(ground_truth_points[:2, 42:48],axis=0))` I am not sure, wanting your kind respond!

**Comment by D-X-Y** [comment]
The interocular distance is `np.linalg.norm(ground_truth_points[:2, 36] - ground_truth_points[:2, 45])`. `interocular_distance = np.linalg.norm(np.mean(ground_truth_points[:2, 36:42],axis=0) - np.mean(ground_truth_points[:2, 42:48],axis=0))` is the inter-pupil distance.

**Comment by wqz960** [comment]
@D-X-Y  But I think in your paper such as SBR and SAN. the error from SDM LBF MDM... is normalized by inter-pupil distance, and errors of your CPM or SAN in your paper  are normalized by inter-ocular distance. About experiments data, you can refer to another paper(Deep Alignment Network). I dont know which is right...

**Comment by D-X-Y** [comment]
@wqz960 Thanks for this reference!
When we submit the paper, we directly use the results from this CVPR 2017 paper (http://openaccess.thecvf.com/content_cvpr_2017/papers/Lv_A_Deep_Regression_CVPR_2017_paper.pdf) without checking these numbers. They noticed that inter-ocular is used.
After several months, we also noticed this problem while cannot change the camera-ready version. Many previous papers do not mention how they normalize on 300-W. And some claim that they use inter-ocular but might use inter-pupil actually. We are also confused. In our following papers (under review), we have used both inter-pupil normalization and inter-ocular normalization.

**Comment by wqz960** [comment]
@D-X-Y Yes!!! This really confuses me, some papers think inter-pupil and inter-ocular are the same,  but the  errors normalized by different error have a big difference. Thank you for your quick respond!

**Comment by D-X-Y** [comment]
@wqz960 You are welcome. These two distance will result in a big different error. I found that more and more recent papers start to show results using both two normalization distances, e.g., http://openaccess.thecvf.com/content_cvpr_2018/papers/Wu_Look_at_Boundary_CVPR_2018_paper.pdf
