### ISSUE TITLE
About speeding up the LK

### ISSUE THREAD

**Issue by zhang-zx** [facebookresearch/supervision-by-registration#46]
In the former issues, you have mentioned that you have made the lk faster and the paper is coming out very soon? Is it published now? Can't wait to read your next wonderful paper!!

**Comment by D-X-Y** [comment]
Thanks for your interest! We just finished the preliminary version and are working on polish. Should be public on arXiv soon. Thanks for your patience.

**Comment by zhang-zx** [comment]
That will be great! Really look forward to it!
