### ISSUE TITLE
Doubts about Video Tags

### ISSUE THREAD

**Issue by zrqi** [facebookresearch/supervision-by-registration#48]
Hello, author, thank you for contributing the code, I have a question about the video label in the SBR process. According to what you said in the paper, the video can be unlabeled, but in the SBR process, the frame t-1 should be labeld? I still have the other question. Since each frame requires the position information of the previous frame, is it necessary to give a label to each frame during training? Because each frame is the previous frame of another frame.

**Comment by D-X-Y** [comment]
Thanks for your interest. The frame t-1 is not necessary to be labeled. Each frame requires the position information of the previous frame, which is provided by the learned detector instead of the manual label.

**Comment by zrqi** [comment]
In the detection loss, you need to calculate the loss between the annotation and the detection results. Isn't this calculated for frame t-1?

**Comment by D-X-Y** [comment]
You can calculate the detection loss for any labeled data (not necessary to be frame t-1). We use frame t-1 as an example to visualize our high-level idea in a simple way.

**Comment by zrqi** [comment]
Oh! I see，thank you
