### ISSUE TITLE
demo-detsbr-vis.mp4 and demo-sbr-vis.mp4 have almost no differences?

### ISSUE THREAD

**Issue by CodingMice** [facebookresearch/supervision-by-registration#52]
Thank you for your code.  I test the code by following the Trainning constructions. Finally I got demo-detsbr-vis.mp4 and demo-sbr-vis.mp4. However,  I found there is alomost no differences in these two video, what is wrong?

**Comment by D-X-Y** [comment]
Would you mind to share the training log and your videos?
