### ISSUE TITLE
maybe something wrong in transforms.py

### ISSUE THREAD

**Issue by momiji7** [facebookresearch/supervision-by-registration#53]
In the 329th line  'x2<0' should be 'y1 < 0', also in the 320th line.

**Comment by D-X-Y** [comment]
Thank you for pointing this bug! I will fix it in `https://github.com/D-X-Y/landmark-detection/tree/master/SBR`, since I do not have access to this repo now.

**Comment by endoplasmic1357** [comment]
Updated transforms.py
