### ISSUE TITLE
the LK operation is very slow, is this normal?

### ISSUE THREAD

**Issue by tubb-lab** [facebookresearch/supervision-by-registration#54]
Thanks for your great work.  I am trying to use the LK operation in my own work , and i have a question about the Lk operation, i put the LK  behind my landmarks model, and i find the LK operation is very slow in the forward propagation, the utilization of gpu is low, is this normal? 
Batch_SIZE = 64,  INPUT_SIZE =128,  single gpu

![image](https://user-images.githubusercontent.com/8148510/60174824-7df64380-9844-11e9-8b71-a6265c63b9a8.png)

**Comment by taozhiiq** [comment]
Thanks for your great work.  I am trying to use the LK operation in my own work , and i have a question about the Lk operation, i put the LK  behind my landmarks model, and i find the LK operation is very slow in the forward propagation, the utilization of gpu is low, is this normal? 
Batch_SIZE = 64,  INPUT_SIZE =128,  single gpu

![image](https://user-images.githubusercontent.com/8148510/60174824-7df64380-9844-11e9-8b71-a6265c63b9a8.png)

**Comment by D-X-Y** [comment]
That is normal because we did not optimize its implementation.
