### ISSUE TITLE
Train my own dataset

### ISSUE THREAD

**Issue by abdou31** [facebookresearch/supervision-by-registration#55]
## Issue description

Can I use this project (supervision-by-registration) to train my own dataset?
If yes, what instructions should I follow? 
Thanks

## System Info
Windows 10 x64

**Comment by D-X-Y** [comment]
You need to generate a file list of your dataset, including some necessary information such as image-path, face bounding box, landmark locations. An example of 300-W is at https://github.com/facebookresearch/supervision-by-registration/blob/master/cache_data/generate_300W.py.

**Comment by abdou31** [comment]
Actually , the result that I hope to get looks like this:

![dsaa](https://user-images.githubusercontent.com/19480228/60262419-68355c80-98de-11e9-9441-60aaf0af7fbb.PNG)

Is it possible with this tool?
If yes, that's good but maybe the one thing that can be so hard is labelling image according to this result ( labelling the iris region )

**Comment by D-X-Y** [comment]
Yes, this repo can train a detector to predict eye-landmarks. But you need to feed it with the corresponding annotations for training.

**Comment by abdou31** [comment]
I have two questions:
+ Did can this repo support detection in real time?
+ Can I use this repo to detect eye region with Android device ( using, for example, frontal camera )?

**Comment by D-X-Y** [comment]
1, What device do you plan to run the model on for real-time-detection?

2, The model can be used to detect, while this repo does not support the Andrioid platform.

**Comment by abdou31** [comment]
1. I want to run the model for real-time-detection on Android device (e.g Samsung A3 2016).
2. Is it supported in the Android platform? ( I mean the extension of the model, e.g tflite* extension is supported on Android device )
+ *tflite extension is the extension of Tensorflow model on the device.

**Comment by AaronXinWu** [comment]
> 1. I want to run the model for real-time-detection on Android device (e.g Samsung A3 2016).
> 2. Is it supported in the Android platform? ( I mean the extension of the model, e.g tflite* extension is supported on Android device )
> 
> * *tflite extension is the extension of Tensorflow model on the device.
same question

**Comment by D-X-Y** [comment]
Sorry for the late reply. The model might be possible to run on Android device, but we did not test it on edge devices. You need to convert the model to tflite models so as to run on Android platform.
