### ISSUE TITLE
About how get the landmark of Reg

### ISSUE THREAD

**Issue by xyzhai-pro** [facebookresearch/supervision-by-registration#57]
Thanks for your wonderful work. I want to use the LK in Regression framework, but i meet a question: to get true landmark, i need some procedure (i.e. face detection, preprocess face and so on)just for an image ; how can I fix the **forward of LK** to flow the gradient of detector?

**Comment by D-X-Y** [comment]
What do you mean "fix the forward of LK"? You want the LK to not back-propagate?

**Comment by xyzhai-pro** [comment]
> What do you mean "fix the forward of LK"? You want the LK to not back-propagate?
Thank you for your answer. The question is that I use the trained regression model and join LK loss to continue training, but the accuracy of landmarks detected by the model is dropped, and deviation is very big. Where is the problem likely to occur? Look forward to your reply.

**Comment by D-X-Y** [comment]
How do you train your regression model and which LK loss do you use?

**Comment by xyzhai-pro** [comment]
> How do you train your regression model and which LK loss do you use?
First, I used the labeled data to train a regression model; second, I added the LK loss (just for unlabeled video consecutive data) to continue to train the model. And the final model has big deviation

**Comment by xyzhai-pro** [comment]
> How do you train your regression model and which LK loss do you use?
In the first phase, just for common training for regression landmarks. In the second phase, I used the regression loss and Lk loss (the function "lk_target_loss" in your code) to train the final model of the first phase.
