### ISSUE TITLE
Seems train_lists in demo_sbr.sh and sbr_example.sh are inconsistent

### ISSUE THREAD

**Issue by qiexing** [facebookresearch/supervision-by-registration#6]
It's very kind of you to share the code.
In scripts folder,
The train_lists in demo_sbr.sh is:
![demo_sbr](https://user-images.githubusercontent.com/8178397/41903535-c4ed33ee-7968-11e8-8fc9-9e67dfbce59f.png)
The train_list in sbr_examples.sh is:
![sbr_example](https://user-images.githubusercontent.com/8178397/41903608-f0e1f750-7968-11e8-905a-eb3a2ed3061b.png)
But demo-sbr.list has no annotation.
I just wonder to train the with-sbr model, which one should I refer to.
Thanks!

**Comment by D-X-Y** [comment]
In demo_sbr.sh, demo-sbr.list has no annotation (dataset_without_annotation) and 300w.train.DET(dataset_with_annotation) has the annotation. It is consistent with sbr_examples.sh.

**Comment by endoplasmic1357** [comment]
The ordering of train_lists is agnostic to whether the file list provided has annotations or not, so you can change the ordering of labeled/unlabeled lists either way and you are fine.

**Comment by qiexing** [comment]
Thanks!
