### ISSUE TITLE
Training problem in the first stage

### ISSUE THREAD

**Issue by KeyKy** [facebookresearch/supervision-by-registration#66]
After modified SBR training, I get a few badcase when testing in a video. These badcases only occur in some frame.
![image](https://user-images.githubusercontent.com/2967075/69328610-7ec3c200-0c8a-11ea-8884-1a338fcef5cc.png)
![image](https://user-images.githubusercontent.com/2967075/69328617-82574900-0c8a-11ea-853f-d82525302bba.png)
![image](https://user-images.githubusercontent.com/2967075/69328628-84b9a300-0c8a-11ea-9ade-fe6950a324aa.png)
it's so weird. I have trained it with a large dataset.

**Comment by KeyKy** [comment]
Does somebody have the same issue as I describle, thanks

**Comment by D-X-Y** [comment]
This does happen sometimes. I also observe this phenomenon.

**Comment by KeyKy** [comment]
OK，I am going to use flip augmentation. Do more experiments.

**Comment by KeyKy** [comment]
could you explain the following code in basic_batch.py?
```
x = x * downsample + downsample / 2.0 - 0.5
y = y * downsample + downsample / 2.0 - 0.5 # why do we need to add the offset?
```

Could you explain this to me? I fix the problem now and i am going to close this issue. @D-X-Y
