### ISSUE TITLE
Result for pretrained model is very bad and unstable at angled face. Is the pretrained model that bad?

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/supervision-by-registration#69]
![Selection_008](https://user-images.githubusercontent.com/10518587/76817598-4a2dd480-683e-11ea-906c-90b945a54666.png)

**Comment by D-X-Y** [comment]
I think so, the model is trained for 300W, where most faces are frontal

**Comment by yxchng** [comment]
@D-X-Y So the pretrained model given in this repo and the one used in the paper are different?

**Comment by D-X-Y** [comment]
Pre-trained model for 300W should be the same

**Comment by yxchng** [comment]
@D-X-Y But it is not the best model? I only find one pretrained model here. Is there more?

**Comment by D-X-Y** [comment]
What dataset do you want to evaluate? It depends on the data.

**Comment by yxchng** [comment]
@D-X-Y I am not trying to evaluate. I am trying to use the model. And right now this pretrained model seems to be very bad. Is `cpm_vgg16-epoch-049-050.pth` the only pretrained model you are releasing? Will I be able to use other pretrained model?

It is even worse than random simple model in the wild like https://github.com/610265158/Peppa_Pig_Face_Engine this one, which is very weird because CVPR models should be good? So I am just curious if there is anything I am doing wrong.

**Comment by D-X-Y** [comment]
This released model is only trained by about 3K labeled images but CPM-VGG16 is quite large and requires a large amount of data to train. So I'm not surprised about its high generalization error.

If you want to use it, I would prefer not to use this pre-trained model but to re-train a new light-weight model with as much data you can collect. Besides, to use a facial landmark detection model, it is better to use the same facial bounding box detector as that used during training. Some facial landmark detectors can be largely affected by the bounding box.

For CVPR, it might be not necessary to have a good model? Our SBR aims to enhance existing models by using a large amount of unlabeled data. For the referred one, one can also use our SBR to improve its performance.

**Comment by yxchng** [comment]
@D-X-Y Ok. Thanks a lot for the info. It is a great work btw!

**Comment by D-X-Y** [comment]
You are always welcome!
