### ISSUE TITLE
About time cost

### ISSUE THREAD

**Issue by Dugudaibo** [facebookresearch/supervision-by-registration#9]
Thank you for your code. I have read you paper but I didn't find the information about its speed, such as 50 fps in  300VW on GPU 1080Ti.  Could you give some information about its speed?

**Comment by D-X-Y** [comment]
Hi, I only have the roughly time cost. For the evaluation, it takes less than 3 minutes to run on the 300W full testing set when using 1080Ti. For the training procedure, since LK costs a lot of time, I remember it takes several days to train on 4 Titan V GPUs.

**Comment by Dugudaibo** [comment]
When you testing, how many GPUs did use~

**Comment by Dugudaibo** [comment]
Sorry ,when you evaluation, not test~

**Comment by D-X-Y** [comment]
two 1080Ti

**Comment by Dugudaibo** [comment]
thanks a lot ~

**Comment by Dugudaibo** [comment]
I am Sorry. Is it 300 W or 300VW that you said you evaluated on.

**Comment by D-X-Y** [comment]
Yes, 300W.

**Comment by Dugudaibo** [comment]
OK , Thank you very much

**Comment by D-X-Y** [comment]
You are welcome~
